### ISSUE TITLE
Drafted the Example Usage 

### ISSUE THREAD

**Issue by zth96** [UBC-MDS/TidyverseToPandas#43]
I have drafted the Milestone 3 example of usage part. Please review, edit and comment.

**Comment by farrandi** [comment]
https://altair-viz.github.io/case_studies/exploring-weather.html

**Comment by farrandi** [comment]
- `example.ipynb`: simple usage of our functions (similar to our docs + testcases)
- `tutorial.ipynb`: more complex usage, showcasing the function in a "full" data science project
